GET http://localhost:3000/
###

POST http://localhost:3000/signin/
Content-Type: application/json

{
    "name":"phhhn",
    "password":"prashh@2023"
}

POST http://localhost:3000/login/
Content-Type: application/json

{
    "name": "vamsi",
    "password": "vamsi@2023"
}
